In [1]:
from proyector import Proyector, np

In [2]:
proy = Proyector( np.deg2rad( 60 ), 100, 1 )
proy.proyection_matrix

array([[ 0.57735027,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.57735027,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  1.01161406, -1.16140592],
       [ 0.        ,  0.        ,  1.        ,  0.        ]])

In [6]:
vertices = [ [ -1, 1, 2, 1 ], [ -1, -1, 2, 1 ], [ 1, -1, 2, 1 ] ]
v1, v2, v3 = proy.proyect_tri( vertices )

tri_coords = [ v1[:2], v2[:2], v3[:2] ]

[(v+1)*np.array([800/2, 800/2]) for v in [ v1[:2], v2[:2], v3[:2] ]]

[array([284.52994616, 515.47005384]),
 array([284.52994616, 284.52994616]),
 array([515.47005384, 284.52994616])]

In [ ]:
np.array( [ [1, 2, 3], [0]*3, [0]*3 ] )@[1 ,1, 1]